/**
 * Pure helpers behind `npm run setup`.
 *
 * Everything here is deliberately free of I/O side effects and console output so
 * it can be unit-tested directly. The interactive shell lives in `setup.ts`.
 */

import { homedir } from "node:os";
import { join } from "node:path";

/** Keys the wizard knows how to fill in, in the order it asks for them. */
export interface FieldSpec {
  readonly key: string;
  readonly label: string;
  readonly required: boolean;
  readonly secret: boolean;
  readonly help: string;
}

/**
 * Fields prompted for when absent.
 *
 * Only genuinely per-install values are listed. Everything else has a working
 * default in `.env.example`, and asking for values that already have sensible
 * defaults is what makes a setup wizard annoying.
 */
export const FIELDS: readonly FieldSpec[] = [
  {
    key: "DISCORD_TOKEN",
    label: "Discord bot token",
    required: true,
    secret: true,
    help: "Developer Portal -> your app -> Bot -> Reset Token. Copy the value.",
  },
  {
    key: "DISCORD_APPLICATION_ID",
    label: "Discord application ID",
    required: true,
    secret: false,
    help: "Developer Portal -> your app -> General Information -> Application ID.",
  },
  {
    key: "DISCORD_ADMIN_USER_IDS",
    label: "Discord user IDs allowed to run admin commands",
    required: true,
    secret: false,
    help: "Discord -> Settings -> Advanced -> Developer Mode, then right-click yourself -> Copy User ID.",
  },
  {
    key: "MOD_API_SECRET",
    label: "Mod API secret",
    required: true,
    secret: true,
    help: "Read automatically from the mod's unionkitbot.secret file when found.",
  },
];

/** Result of merging values into an existing `.env` document. */
export interface MergeResult {
  readonly text: string;
  readonly applied: readonly string[];
  readonly appended: readonly string[];
}

const KEY_PATTERN = /^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=/;

/**
 * Quotes a value when a dotenv parser could otherwise misread it.
 *
 * @param value the raw value
 * @returns the value as it should appear after `=`
 */
export function formatEnvValue(value: string): string {
  const needsQuotes = /\s|#|"|'/.test(value);
  if (!needsQuotes) {
    return value;
  }
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

/**
 * Fills assignments into an `.env` document, leaving everything else untouched.
 *
 * Existing lines are rewritten in place so comments stay next to the key they
 * describe, and keys that are not part of the update are never dropped. This is
 * what makes re-running the wizard safe.
 *
 * @param existing the current file contents, or `undefined` when absent
 * @param assignments the key/value pairs to apply
 * @returns the new document plus what was changed
 */
export function mergeEnvFile(
  existing: string | undefined,
  assignments: ReadonlyMap<string, string>,
): MergeResult {
  const remaining = new Map(assignments);
  const applied: string[] = [];
  const lines: string[] = [];

  if (existing === undefined) {
    lines.push("# Generated by `npm run setup`. Never commit this file.");
    lines.push("");
  } else {
    for (const rawLine of existing.split(/\r?\n/)) {
      const match = KEY_PATTERN.exec(rawLine);
      const key = match?.[1];
      if (key === undefined || !remaining.has(key)) {
        lines.push(rawLine);
        continue;
      }
      const value = remaining.get(key);
      if (value === undefined) {
        lines.push(rawLine);
        continue;
      }
      lines.push(`${key}=${formatEnvValue(value)}`);
      applied.push(key);
      remaining.delete(key);
    }
  }

  const appended: string[] = [];
  if (remaining.size > 0) {
    if (lines.length > 0 && lines[lines.length - 1] !== "") {
      lines.push("");
    }
    lines.push("# Added by `npm run setup`.");
    for (const [key, value] of remaining) {
      lines.push(`${key}=${formatEnvValue(value)}`);
      appended.push(key);
    }
  }

  // Exactly one trailing newline, and never zero.
  const text = `${lines.join("\n").replace(/\n+$/, "")}\n`;
  return { text, applied, appended };
}

/**
 * Reads the values already present in an `.env` document.
 *
 * @param text the file contents
 * @returns a map of non-empty values, with an absent file yielding an empty map
 */
export function readEnvFile(text: string | undefined): Map<string, string> {
  const values = new Map<string, string>();
  if (text === undefined) {
    return values;
  }
  for (const rawLine of text.split(/\r?\n/)) {
    const trimmed = rawLine.trim();
    if (trimmed === "" || trimmed.startsWith("#")) {
      continue;
    }
    const separator = trimmed.indexOf("=");
    if (separator <= 0) {
      continue;
    }
    const key = trimmed.slice(0, separator).trim();
    let value = trimmed.slice(separator + 1).trim();
    if (
      value.length >= 2 &&
      ((value.startsWith('"') && value.endsWith('"')) ||
        (value.startsWith("'") && value.endsWith("'")))
    ) {
      value = value.slice(1, -1);
    }
    if (value !== "") {
      values.set(key, value);
    }
  }
  return values;
}

/**
 * Candidate locations of the mod's configuration directory.
 *
 * The list is ordered most-specific first. None of these are guaranteed to
 * exist; the wizard simply uses the first one that contains a secret file.
 *
 * @param platform the value of `process.platform`
 * @param env the process environment
 * @returns candidate directory paths
 */
export function modConfigCandidates(
  platform: NodeJS.Platform,
  env: NodeJS.ProcessEnv,
): readonly string[] {
  const candidates: string[] = [];
  const explicit = env["UNIONKITBOT_MOD_DIR"];
  if (explicit !== undefined && explicit.trim() !== "") {
    candidates.push(explicit.trim());
    return candidates;
  }

  const home = env["HOME"] ?? env["USERPROFILE"] ?? homedir();
  const appData = env["APPDATA"];

  if (platform === "darwin") {
    candidates.push(join(home, "Library", "Application Support", "minecraft", "config", "unionkitbot"));
  } else if (platform === "win32") {
    if (appData !== undefined && appData.trim() !== "") {
      candidates.push(join(appData, ".minecraft", "config", "unionkitbot"));
    }
    candidates.push(join(home, "AppData", "Roaming", ".minecraft", "config", "unionkitbot"));
  } else {
    candidates.push(join(home, ".minecraft", "config", "unionkitbot"));
  }
  return candidates;
}

/** Outcome of validating the values destined for `.env`. */
export interface ValidationIssue {
  readonly key: string;
  readonly message: string;
}

const SNOWFLAKE = /^\d{5,32}$/;

/**
 * Checks the values the wizard collected.
 *
 * @param values the candidate values
 * @returns every problem found, empty when the values are usable
 */
export function validateValues(values: ReadonlyMap<string, string>): readonly ValidationIssue[] {
  const issues: ValidationIssue[] = [];

  for (const field of FIELDS) {
    if (!field.required) {
      continue;
    }
    const value = values.get(field.key);
    if (value === undefined || value.trim() === "") {
      issues.push({ key: field.key, message: "is required" });
    }
  }

  const admins = values.get("DISCORD_ADMIN_USER_IDS");
  if (admins !== undefined && admins.trim() !== "") {
    for (const id of admins.split(",").map((part) => part.trim()).filter((part) => part !== "")) {
      if (!SNOWFLAKE.test(id)) {
        issues.push({ key: "DISCORD_ADMIN_USER_IDS", message: `'${id}' is not a Discord user ID` });
      }
    }
  }

  const token = values.get("DISCORD_TOKEN");
  if (token !== undefined && token.trim() !== "" && !/^[A-Za-z0-9._-]{20,}$/.test(token.trim())) {
    issues.push({ key: "DISCORD_TOKEN", message: "does not look like a bot token" });
  }

  const applicationId = values.get("DISCORD_APPLICATION_ID");
  if (applicationId !== undefined && applicationId.trim() !== "" && !SNOWFLAKE.test(applicationId.trim())) {
    issues.push({ key: "DISCORD_APPLICATION_ID", message: "is not a Discord application ID" });
  }

  const secret = values.get("MOD_API_SECRET");
  if (secret !== undefined && secret.trim() !== "" && secret.trim().length < 16) {
    issues.push({ key: "MOD_API_SECRET", message: "must be at least 16 characters" });
  }

  return issues;
}

/**
 * @param values the collected values
 * @returns the fields still missing a value
 */
export function missingFields(values: ReadonlyMap<string, string>): readonly FieldSpec[] {
  return FIELDS.filter((field) => {
    const value = values.get(field.key);
    if (value === undefined || value.trim() === "") {
      return true;
    }
    // A leftover placeholder from .env.example is not a real value.
    return /^(<.*>|your-.*|changeme)$/i.test(value.trim());
  });
}
